from aipinho.schemas.patching.apply.hunk_apply_result import HunkApplyResult
from aipinho.schemas.patching.apply.patch_apply_backup import PatchApplyBackup
from aipinho.schemas.patching.apply.patch_apply_event import PatchApplyEvent
from aipinho.schemas.patching.apply.patch_apply_file_result import PatchApplyFileResult
from aipinho.schemas.patching.apply.patch_apply_guard import PatchApplyGuardResult
from aipinho.schemas.patching.apply.patch_apply_policy import PatchApplyPolicy
from aipinho.schemas.patching.apply.patch_apply_request import PatchApplyRequest
from aipinho.schemas.patching.apply.patch_apply_result import PatchApplyResult
from aipinho.schemas.patching.apply.patch_apply_run import PatchApplyRun
from aipinho.schemas.patching.apply.patch_apply_status import PatchApplyStatus
from aipinho.schemas.patching.apply.patch_apply_trace import PatchApplyTrace
from aipinho.schemas.patching.apply.post_apply_validation import PostApplyValidation
from aipinho.schemas.patching.apply.rollback_result import RollbackResult
