from __future__ import annotations

from pathlib import Path

from aipinho.core.paths import PATHS
from aipinho.utils.yaml_loader import inspect_yaml_file

CRITICAL_CONFIGS = (
    "config/supervisor/service_manifest.yaml",
    "config/supervisor/supervisor_policy.yaml",
    "config/supervisor/service_restart_policy.yaml",
    "config/supervisor/port_monitor_policy.yaml",
    "config/supervisor/resource_monitor_policy.yaml",
    "config/supervisor/launcher_policy.yaml",
    "config/supervisor/connection_profiles.yaml",
    "config/supervisor/adb_reverse_policy.yaml",
    "config/supervisor/wifi_lan_policy.yaml",
    "config/supervisor/tailscale_policy.yaml",
    "config/supervisor/mobile_pairing_policy.yaml",
    "config/supervisor/token_auth_policy.yaml",
    "config/supervisor/monitor_event_policy.yaml",
    "config/supervisor/human_health_policy.yaml",
    "config/realtime/realtime_policy.yaml",
    "config/artifacts/artifact_service_policy.yaml",
    "config/app/identity.yaml",
    "config/app/product.yaml",
    "config/policies/policy_precedence.yaml",
    "config/policies/action_registry.yaml",
    "config/policies/capability_registry.yaml",
    "config/policies/approval_policy.yaml",
    "config/policies/prompt_intelligence_policy.yaml",
    "config/policies/intent_taxonomy.yaml",
    "config/policies/concept_registry.yaml",
    "config/policies/ambiguity_policy.yaml",
    "config/policies/risk_policy.yaml",
    "config/policies/chat_dispatch_policy.yaml",
    "config/policies/self_knowledge_sources.yaml",
    "config/policies/task_contract_policy.yaml",
    "config/policies/task_draft_policy.yaml",
    "config/runtime/session_policy.yaml",
    "config/runtime/task_draft_policy.yaml",
    "config/runtime/retention_policy.yaml",
    "config/security/redaction_policy.yaml",
    "config/policies/approval_lifecycle_policy.yaml",
    "config/policies/preview_policy.yaml",
    "config/runtime/approval_store_policy.yaml",
    "config/runtime/preview_store_policy.yaml",
    "config/ux/approval_response_policy.yaml",
    "config/tools/tool_registry.yaml",
    "config/tools/filesystem_tools.yaml",
    "config/tools/shell_tools.yaml",
    "config/tools/git_tools.yaml",
    "config/tools/android_tools.yaml",
    "config/tools/web_tools.yaml",
    "config/policies/tool_policy.yaml",
    "config/policies/tool_dry_run_policy.yaml",
    "config/security/sandbox_policy.yaml",
    "config/security/path_guard_policy.yaml",
    "config/security/secret_policy.yaml",
    "config/policies/read_only_execution_policy.yaml",
    "config/analysis/project_analysis_policy.yaml",
    "config/analysis/file_context_policy.yaml",
    "config/analysis/project_tree_policy.yaml",
    "config/analysis/file_selection_policy.yaml",
    "config/analysis/architecture_analysis_policy.yaml",
    "config/analysis/ignore_patterns.yaml",
    "config/reports/project_report_policy.yaml",
    "config/reports/finding_rules.yaml",
    "config/reports/severity_policy.yaml",
    "config/reports/report_templates.yaml",
    "config/reports/evidence_policy.yaml",
    "config/reports/citation_policy.yaml",
    "config/reports/recommendation_policy.yaml",
    "config/runtime/execution_audit_policy.yaml",
    "config/ux/chat_response_policy.yaml",
    "config/ux/speaker_policy.yaml",
    "config/roles/default_roles.yaml",
    "config/roles/role_pipelines.yaml",
    "config/roles/role_model_policy.yaml",
    "config/roles/role_model_bindings.yaml",
    "config/roles/role_inference_policy.yaml",
    "config/roles/role_inference_budget_policy.yaml",
    "config/roles/role_model_fallback_policy.yaml",
    "config/roles/manual_escalation_policy.yaml",
    "config/roles/role_prompt_contracts.yaml",
    "config/roles/role_model_trace_policy.yaml",
    "config/roles/role_model_run_store_policy.yaml",
    "config/roles/role_output_contracts.yaml",
    "config/roles/role_prompt_policy.yaml",
    "config/roles/role_fallback_policy.yaml",
    "config/roles/role_pipeline_policy.yaml",
    "config/roles/effective_role_policy.yaml",
    "config/workspaces/protected_workspaces.yaml",
    "config/workspaces/workspace_resolution_policy.yaml",
    "config/governance/runtime_profiles.yaml",
    "config/models/model_registry.yaml",
    "config/models/provider_registry.yaml",
    "config/models/model_provider_registry.yaml",
    "config/models/model_capabilities.yaml",
    "config/models/model_runtime_policy.yaml",
    "config/models/model_doctor_policy.yaml",
    "config/models/model_probe_policy.yaml",
    "config/models/model_hardware_policy.yaml",
    "config/models/model_latency_policy.yaml",
    "config/models/model_security_policy.yaml",
    "config/models/role_model_candidates.yaml",
    "config/models/manual_model_escalation_policy.yaml",
    "config/models/model_routing_policy.yaml",
    "config/models/generation_defaults.yaml",
    "config/models/local_provider_policy.yaml",
    "config/models/real_inference_gate.yaml",
    "config/models/manual_inference_profiles.yaml",
    "config/models/manual_inference_gate.yaml",
    "config/models/llama_smoke_test_policy.yaml",
    "config/runtime/real_inference_run_store.yaml",
    "config/models/llama_cpp_policy.yaml",
    "config/models/local_model_paths.yaml",
    "config/models/inference_limits.yaml",
    "config/models/model_runtime_profiles.yaml",
    "config/debugger/debug_trace_policy.yaml",
    "config/debugger/model_trace_policy.yaml",
    "config/debugger/debug_sanitization_policy.yaml",
    "config/security/model_process_policy.yaml",
    "config/prompts/prompt_assembly_policy.yaml",
    "config/prompts/prompt_budgets.yaml",
    "config/prompts/role_prompt_templates.yaml",
    "config/prompts/output_contracts.yaml",
    "config/prompts/safety_envelopes.yaml",
    "config/prompts/context_packing_policy.yaml",
    "config/evaluation/model_response_evaluation_policy.yaml",
    "config/evaluation/output_contract_validation_policy.yaml",
    "config/evaluation/safety_validation_policy.yaml",
    "config/evaluation/evidence_validation_policy.yaml",
    "config/evaluation/hallucination_signal_policy.yaml",
    "config/evaluation/truncation_policy.yaml",
    "config/evaluation/retry_policy.yaml",
    "config/evaluation/fallback_policy.yaml",
    "config/chat/chat_model_policy.yaml",
    "config/chat/manual_chat_inference_policy.yaml",
    "config/chat/chat_model_fallback_policy.yaml",
    "config/chat/chat_inference_audit_policy.yaml",
    "config/runtime/task_runtime_policy.yaml",
    "config/runtime/task_run_lifecycle_policy.yaml",
    "config/runtime/task_run_store_policy.yaml",
    "config/runtime/task_run_event_policy.yaml",
    "config/runtime/supervised_execution_policy.yaml",
    "config/runtime/readonly_task_steps.yaml",
    "config/runtime/task_runtime_limits.yaml",
    "config/runtime/task_cancellation_policy.yaml",
    "config/runtime/task_result_policy.yaml",
    "config/validation/validation_gate_policy.yaml",
    "config/validation/task_run_validation_policy.yaml",
    "config/validation/report_quality_gate_policy.yaml",
    "config/validation/contract_compliance_policy.yaml",
    "config/validation/evidence_compliance_policy.yaml",
    "config/validation/side_effect_validation_policy.yaml",
    "config/validation/workspace_access_validation_policy.yaml",
    "config/validation/quality_score_policy.yaml",
    "config/validation/validation_audit_policy.yaml",
    "config/validation/validation_store_policy.yaml",
    "config/artifacts/artifact_writer_policy.yaml",
    "config/artifacts/artifact_target_policy.yaml",
    "config/artifacts/artifact_content_policy.yaml",
    "config/artifacts/artifact_format_policy.yaml",
    "config/artifacts/artifact_preview_policy.yaml",
    "config/artifacts/artifact_risk_policy.yaml",
    "config/artifacts/artifact_approval_policy.yaml",
    "config/artifacts/artifact_store_policy.yaml",
    "config/artifacts/artifact_diff_policy.yaml",
    "config/artifacts/artifact_source_policy.yaml",
    "config/artifacts/artifact_write_policy.yaml",
    "config/artifacts/artifact_write_execution_policy.yaml",
    "config/artifacts/artifact_overwrite_policy.yaml",
    "config/artifacts/artifact_atomic_write_policy.yaml",
    "config/artifacts/artifact_backup_policy.yaml",
    "config/artifacts/artifact_post_write_validation_policy.yaml",
    "config/artifacts/artifact_write_store_policy.yaml",
    "config/artifacts/artifact_write_audit_policy.yaml",
    "config/artifacts/artifact_write_lifecycle_policy.yaml",
    "config/patching/patch_planning_policy.yaml",
    "config/patching/patch_scope_policy.yaml",
    "config/patching/patch_target_policy.yaml",
    "config/patching/diff_proposal_policy.yaml",
    "config/patching/patch_evidence_policy.yaml",
    "config/patching/patch_risk_policy.yaml",
    "config/patching/patch_validation_policy.yaml",
    "config/patching/rollback_note_policy.yaml",
    "config/patching/patch_test_recommendation_policy.yaml",
    "config/patching/patch_store_policy.yaml",
    "config/patching/patch_audit_policy.yaml",
    "config/patching/quality/patch_quality_gate_policy.yaml",
    "config/patching/quality/static_validation_policy.yaml",
    "config/patching/quality/diff_parse_policy.yaml",
    "config/patching/quality/hunk_validation_policy.yaml",
    "config/patching/quality/target_snapshot_validation_policy.yaml",
    "config/patching/quality/syntax_validation_policy.yaml",
    "config/patching/quality/hardcode_detection_policy.yaml",
    "config/patching/quality/policy_bypass_detection_policy.yaml",
    "config/patching/quality/security_regression_policy.yaml",
    "config/patching/quality/import_impact_policy.yaml",
    "config/patching/quality/schema_api_impact_policy.yaml",
    "config/patching/quality/test_plan_validation_policy.yaml",
    "config/patching/quality/rollback_validation_policy.yaml",
    "config/patching/quality/patch_quality_score_policy.yaml",
    "config/patching/quality/patch_quality_store_policy.yaml",
    "config/patching/quality/patch_quality_audit_policy.yaml",
    "config/patching/apply/patch_apply_policy.yaml",
    "config/patching/apply/patch_apply_execution_policy.yaml",
    "config/patching/apply/patch_apply_guard_policy.yaml",
    "config/patching/apply/patch_apply_approval_policy.yaml",
    "config/patching/apply/patch_apply_backup_policy.yaml",
    "config/patching/apply/patch_apply_atomic_write_policy.yaml",
    "config/patching/apply/post_apply_validation_policy.yaml",
    "config/patching/apply/patch_apply_store_policy.yaml",
    "config/patching/apply/patch_apply_audit_policy.yaml",
    "config/patching/apply/patch_apply_lifecycle_policy.yaml",
    "config/patching/apply/patch_rollback_policy.yaml",
    "config/patching/apply/workspace_mutation_tracking_policy.yaml",
    "config/memory/memory_candidate_policy.yaml",
    "config/memory/memory_candidate_source_policy.yaml",
    "config/memory/memory_candidate_extraction_policy.yaml",
    "config/memory/memory_candidate_validation_policy.yaml",
    "config/memory/memory_candidate_scope_policy.yaml",
    "config/memory/memory_candidate_evidence_policy.yaml",
    "config/memory/memory_candidate_risk_policy.yaml",
    "config/memory/memory_candidate_dedupe_policy.yaml",
    "config/memory/memory_candidate_conflict_policy.yaml",
    "config/memory/memory_candidate_sensitivity_policy.yaml",
    "config/memory/memory_candidate_store_policy.yaml",
    "config/memory/memory_candidate_audit_policy.yaml",
    "config/memory/memory_candidate_lifecycle_policy.yaml",
    "config/memory/curated_memory_policy.yaml",
    "config/memory/memory_approval_policy.yaml",
    "config/memory/memory_persistence_policy.yaml",
    "config/memory/curated_memory_store_policy.yaml",
    "config/memory/curated_memory_validation_policy.yaml",
    "config/memory/curated_memory_scope_policy.yaml",
    "config/memory/curated_memory_evidence_policy.yaml",
    "config/memory/curated_memory_versioning_policy.yaml",
    "config/memory/curated_memory_dedupe_policy.yaml",
    "config/memory/curated_memory_conflict_policy.yaml",
    "config/memory/curated_memory_search_policy.yaml",
    "config/memory/curated_memory_read_policy.yaml",
    "config/memory/curated_memory_audit_policy.yaml",
    "config/memory/curated_memory_lifecycle_policy.yaml",
    "config/rag/retrieval_policy.yaml",
    "config/rag/retrieval_source_registry.yaml",
    "config/rag/retrieval_source_policy.yaml",
    "config/rag/retrieval_scope_policy.yaml",
    "config/rag/retrieval_budget_policy.yaml",
    "config/rag/retrieval_ranking_policy.yaml",
    "config/rag/retrieval_context_policy.yaml",
    "config/rag/evidence_bundle_policy.yaml",
    "config/rag/citation_policy.yaml",
    "config/rag/retrieval_sensitivity_policy.yaml",
    "config/rag/retrieval_audit_policy.yaml",
    "config/rag/retrieval_store_policy.yaml",
    "config/rag/legacy_rag_block_policy.yaml",
    "config/rag/vector_rag_policy.yaml",
    "config/rag/vector_index_registry.yaml",
    "config/rag/legacy_rag_import_policy.yaml",
    "config/rag/legacy_rag_namespace_policy.yaml",
    "config/rag/legacy_rag_sanitization_policy.yaml",
    "config/rag/legacy_rag_classification_policy.yaml",
    "config/rag/legacy_rag_conflict_policy.yaml",
    "config/rag/legacy_rag_deprecation_policy.yaml",
    "config/rag/legacy_rag_review_policy.yaml",
    "config/rag/legacy_rag_pinhoforge_policy.yaml",
    "config/rag/legacy_rag_regression_seed_policy.yaml",
    "config/rag/legacy_rag_lesson_policy.yaml",
    "config/rag/vector_store_policy.yaml",
    "config/rag/global_rag_policy.yaml",
    "config/rag/role_rag_policy.yaml",
    "config/rag/role_rag_namespaces.yaml",
    "config/rag/embedding_policy.yaml",
    "config/rag/reranker_policy.yaml",
    "config/rag/chunking_policy.yaml",
    "config/rag/rag_ingestion_policy.yaml",
    "config/rag/rag_ingestion_approval_policy.yaml",
    "config/rag/rag_query_policy.yaml",
    "config/rag/rag_namespace_access_policy.yaml",
    "config/rag/rag_index_doctor_policy.yaml",
    "config/rag/rag_sensitivity_policy.yaml",
    "config/rag/rag_audit_policy.yaml",
    "config/rag/integration/rag_memory_policy.yaml",
    "config/rag/integration/context_admission_policy.yaml",
    "config/rag/integration/context_injection_policy.yaml",
    "config/rag/integration/context_budget_policy.yaml",
    "config/rag/integration/context_provenance_policy.yaml",
    "config/rag/integration/context_citation_map_policy.yaml",
    "config/rag/integration/context_conflict_policy.yaml",
    "config/rag/integration/context_freshness_policy.yaml",
    "config/rag/integration/memory_context_policy.yaml",
    "config/rag/integration/retrieval_context_policy.yaml",
    "config/rag/integration/context_usage_validation_policy.yaml",
    "config/rag/integration/context_usage_audit_policy.yaml",
    "config/events/event_contract_registry.yaml",
    "config/events/event_schema_policy.yaml",
    "config/events/event_visibility_policy.yaml",
    "config/events/event_copy_policy.yaml",
    "config/events/event_severity_policy.yaml",
    "config/events/event_source_policy.yaml",
    "config/events/event_store_policy.yaml",
    "config/events/event_audit_policy.yaml",
    "config/interaction/speaker_truth_policy.yaml",
    "config/interaction/speaker_event_policy.yaml",
    "config/interaction/humanized_log_policy.yaml",
    "config/interaction/interaction_cockpit_policy.yaml",
    "config/interaction/chat_policy.yaml",
    "config/interaction/chat_session_policy.yaml",
    "config/interaction/chat_message_policy.yaml",
    "config/interaction/chat_attachment_policy.yaml",
    "config/interaction/chat_timeline_policy.yaml",
    "config/interaction/sanitized_raw_policy.yaml",
    "config/interaction/copy_action_policy.yaml",
    "config/interaction/feedback_policy.yaml",
    "config/interaction/task_sync_policy.yaml",
    "config/interaction/pipeline_sync_policy.yaml",
    "config/interaction/client_sync_policy.yaml",
    "config/artifacts/artifact_storage_policy.yaml",
    "config/artifacts/artifact_upload_policy.yaml",
    "config/artifacts/artifact_download_policy.yaml",
    "config/artifacts/artifact_zip_policy.yaml",
    "config/artifacts/artifact_security_policy.yaml",
    "config/realtime/event_bus_policy.yaml",
    "config/realtime/sync_policy.yaml",
    "config/policies/decision_ownership_matrix.yaml",
    "config/launcher/desktop_ui_policy.yaml",
    "config/launcher/desktop_ui_tabs.yaml",
    "config/launcher/desktop_ui_event_policy.yaml",
    "config/launcher/desktop_ui_connection_policy.yaml",
    "config/launcher/desktop_ui_token_policy.yaml",
    "config/launcher/desktop_ui_refresh_policy.yaml",
    "config/launcher/desktop_ui_download_policy.yaml",
    "config/launcher/desktop_ui_upload_policy.yaml",
    "config/launcher/desktop_ui_log_policy.yaml",
    "config/launcher/desktop_ui_theme.yaml",
    "config/launcher/desktop_ui_degraded_policy.yaml",
    "config/context/context_kernel_policy.yaml",
    "config/context/context_layer_policy.yaml",
    "config/context/context_purpose_policy.yaml",
    "config/context/context_admission_policy.yaml",
    "config/context/context_budget_policy.yaml",
    "config/context/context_cache_policy.yaml",
    "config/context/context_freshness_policy.yaml",
    "config/context/context_source_policy.yaml",
    "config/context/context_trust_policy.yaml",
    "config/context/context_citation_policy.yaml",
    "config/context/context_dedupe_policy.yaml",
    "config/context/context_compression_policy.yaml",
    "config/context/context_raw_policy.yaml",
    "config/context/context_sensitivity_policy.yaml",
    "config/context/context_prompt_injection_policy.yaml",
    "config/context/context_conflict_policy.yaml",
    "config/context/smart_chunk_policy.yaml",
    "config/context/chunk_classifier_policy.yaml",
    "config/context/context_trace_policy.yaml",
    "config/ux/ux_hardening_policy.yaml",
    "config/ux/degraded_state_policy.yaml",
    "config/ux/notification_policy.yaml",
    "config/ux/human_error_policy.yaml",
    "config/ux/latency_indicator_policy.yaml",
    "config/ux/progress_indicator_policy.yaml",
    "config/ux/copy_action_hardening_policy.yaml",
    "config/ux/session_recovery_policy.yaml",
    "config/ux/approval_clarity_policy.yaml",
    "config/events/event_filter_policy.yaml",
    "config/events/event_search_policy.yaml",
    "config/interaction/raw_viewer_policy.yaml",
    "config/transfers/upload_progress_policy.yaml",
    "config/transfers/download_manager_policy.yaml",
    "config/transfers/transfer_integrity_policy.yaml",
    "config/launcher/desktop_ui_hardening_policy.yaml",
    "config/launcher/desktop_ui_reconnect_policy.yaml",
    "config/launcher/desktop_ui_notification_policy.yaml",
    "config/mobile/mobile_app_policy.yaml",
    "config/mobile/mobile_connection_policy.yaml",
    "config/mobile/mobile_token_policy.yaml",
    "config/mobile/mobile_realtime_policy.yaml",
    "config/mobile/mobile_upload_policy.yaml",
    "config/mobile/mobile_download_policy.yaml",
    "config/mobile/mobile_debugger_policy.yaml",
    "config/mobile/mobile_pipeline_policy.yaml",
    "config/mobile/mobile_dashboard_policy.yaml",
    "config/mobile/mobile_degraded_policy.yaml",
    "config/mobile/mobile_security_policy.yaml",
    "config/skills/skill_runtime_policy.yaml",
    "config/skills/skill_registry_policy.yaml",
    "config/skills/skill_contract_schema.yaml",
    "config/skills/skill_catalog.yaml",
    "config/skills/skill_routing_policy.yaml",
    "config/skills/skill_composition_policy.yaml",
    "config/skills/skill_execution_policy.yaml",
    "config/skills/skill_output_validation_policy.yaml",
    "config/skills/skill_install_policy.yaml",
    "config/skills/skill_creator_policy.yaml",
    "config/skills/skill_risk_policy.yaml",
    "config/skills/skill_anti_trigger_policy.yaml",
    "config/skills/skill_fallback_policy.yaml",
    "config/skills/skill_event_policy.yaml",
    "config/tools/tool_registry.yaml",
    "config/tools/tool_policy.yaml",
    "config/tools/tool_provider_policy.yaml",
    "config/tools/tool_permission_policy.yaml",
    "config/tools/tool_risk_policy.yaml",
    "config/tools/tool_availability_policy.yaml",
    "config/maintenance/maintenance_plane_policy.yaml",
    "config/maintenance/maintenance_modes_policy.yaml",
    "config/maintenance/diagnosis_policy.yaml",
    "config/maintenance/diagnosis_evidence_policy.yaml",
    "config/maintenance/invariant_policy.yaml",
    "config/maintenance/repair_planning_policy.yaml",
    "config/maintenance/repair_proposal_policy.yaml",
    "config/maintenance/repair_handoff_policy.yaml",
    "config/maintenance/maintenance_patch_preview_policy.yaml",
    "config/maintenance/maintenance_config_change_policy.yaml",
    "config/maintenance/maintenance_validation_policy.yaml",
    "config/maintenance/maintenance_rollback_policy.yaml",
    "config/maintenance/maintenance_signal_policy.yaml",
    "config/maintenance/maintenance_lesson_policy.yaml",
    "config/maintenance/autocure_supervision_policy.yaml",
    "config/maintenance/invariant_registry.yaml",
    "config/replay/replay_harness_policy.yaml",
    "config/replay/replay_capture_policy.yaml",
    "config/replay/replay_snapshot_policy.yaml",
    "config/replay/replay_sanitization_policy.yaml",
    "config/replay/replay_runner_policy.yaml",
    "config/replay/replay_diff_policy.yaml",
    "config/replay/replay_store_policy.yaml",
    "config/regression/regression_harness_policy.yaml",
    "config/regression/regression_case_policy.yaml",
    "config/regression/regression_suite_policy.yaml",
    "config/regression/golden_expectation_policy.yaml",
    "config/regression/expectation_evaluator_policy.yaml",
    "config/regression/regression_promotion_policy.yaml",
    "config/regression/regression_report_policy.yaml",
    "config/regression/core_regression_suite.yaml",
    "config/regression/legacy_bug_regression_suite.yaml",
    "config/regression/safety_regression_suite.yaml",
    "config/regression/ux_regression_suite.yaml",
    "config/patching/patch_quality_gate_policy.yaml",
    "config/routes/routes.yaml",
)


def critical_config_status() -> dict[str, object]:
    entries = []
    warnings: list[str] = []
    for relative in CRITICAL_CONFIGS:
        status = inspect_yaml_file(PATHS.project_root / Path(relative), root=PATHS.project_root)
        entries.append(status.__dict__)
        if status.status != "ok":
            warnings.append(f"{relative}: {status.status}")
    feature_flags = {
        "ux_hardening_enabled": True,
        "degraded_states_enabled": True,
        "reconnect_enabled": True,
        "fallback_polling_enabled": True,
        "download_manager_enabled": True,
        "upload_progress_enabled": True,
        "raw_viewer_enabled": True,
        "event_filters_enabled": True,
        "session_recovery_enabled": True,
        "token_redaction_enabled": True,
        "mobile_app_enabled": True,
        "android_app_enabled": True,
        "adb_reverse_supported": True,
        "wifi_lan_supported": True,
        "tailscale_supported": True,
        "manual_profile_supported": True,
        "token_hardcoded": False,
        "mobile_sync_via_backend": True,
        "unknown_event_normal_rendering": False,
        "skill_runtime_enabled": True,
        "skill_real_execution_enabled": False,
        "skill_preview_enabled": True,
        "skill_dry_run_enabled": True,
        "skill_install_real_enabled": False,
        "unknown_skill_blocked": True,
        "critical_skills_disabled": True,
        "direct_shell_blocked": True,
        "direct_patch_apply_blocked": True,
        "external_network_blocked_by_default": True,
        "replay_harness_enabled": True,
        "regression_harness_enabled": True,
        "replay_side_effects_allowed": False,
        "regression_side_effects_allowed": False,
        "model_real_inference_allowed": False,
        "patch_apply_allowed": False,
        "shell_allowed": False,
        "git_allowed": False,
        "external_network_allowed": False,
        "memory_write_allowed": False,
        "maintenance_plane_enabled": True,
        "supervised_autocure_enabled": True,
        "autonomous_apply": False,
        "diagnose_mode_enabled": True,
        "repair_proposal_enabled": True,
        "patch_preview_enabled": True,
        "config_preview_enabled": True,
        "validation_plan_enabled": True,
        "lesson_candidate_enabled": True,
        "direct_policy_write_enabled": False,
        "direct_memory_write_enabled": False,
    }
    return {
        "status": "ok" if not warnings else "degraded",
        "configs": entries,
        "warnings": warnings,
        "feature_flags": feature_flags,
    }






